### ISSUE TITLE
'Vehicle' object has no attribute 'target_speed'

### ISSUE THREAD

**Issue by aseembits93** [Farama-Foundation/HighwayEnv#563] opened 2024-01-23 16:42 UTC
Hi @eleurent ! 

thank you for sharing your work. I started playing around with it and got stuck here. 

```
import gymnasium as gym
env = gym.make("highway-v0")
env.configure({'other_vehicles_type': 'highway_env.vehicle.behavior.AggressiveVehicle','action':{"type": "ContinuousAction"}})
env.reset()
action = env.action_space.sample()
env.step(action)
 ```

This throws an error
`
AttributeError: 'Vehicle' object has no attribute 'target_speed'
`

Let me know how I could resolve this issue, thanks!

**Comment by eleurent** [comment] 2024-01-27 14:56
Hi! Thanks for providing the snippet, I was unable to reproduce the error, see my [attempt on colab](https://colab.research.google.com/drive/1ePId2b-j9xvpcVyPUvJNv7RJS4SpWQyH?usp=sharing).

**Comment by eleurent** [comment] 2024-01-27 15:22
Should be fixed if you install the dev version from the main branch.

**Closed** 2024-01-27 15:22 UTC
