### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by May-fang** [Farama-Foundation/HighwayEnv#461] opened 2023-04-27 08:38 UTC
When I run scripts\sb3_highway_dqn.py,I found AssertionError: The algorithm only supports (<class 'gym.spaces.discrete.Discrete'>,) as action spaces but Discrete(5) was provided, it seems the stable_baselines3 version's problem?May I ask how I should solve this problem？

**Comment by limeng-1234** [comment] 2023-05-03 14:15
I met the same problem

**Comment by eleurent** [comment] 2023-05-07 12:59
Duplicate of e.g. https://github.com/DLR-RM/stable-baselines3/issues/1475

Hi, this is an issue related to gymnasium and SB3's version, not HighwayEnv. They recommend:
`pip install stable-baselines3[extra] --pre --upgrade` (install SB3 v2.0+) or install master version (see documentation).

**Closed** 2023-05-30 22:14 UTC
