### ISSUE TITLE
AttributeError: 'RecordVideo' object has no attribute 'video_recorder'

### ISSUE THREAD

**Issue by carterwg7** [Farama-Foundation/HighwayEnv#631] opened 2024-11-07 21:40 UTC
When using the sb3_highway_dqn.ipynb script, I get the following error when attempting to visualize the episodes:

[/usr/local/lib/python3.10/dist-packages/highway_env/envs/common/abstract.py](https://localhost:8080/#) in _automatic_rendering(self)
    335         """
    336         if self.viewer is not None and self.enable_auto_render:
--> 337             if self._record_video_wrapper and self._record_video_wrapper.video_recorder:
    338                 self._record_video_wrapper.video_recorder.capture_frame()
    339             else:

AttributeError: 'RecordVideo' object has no attribute 'video_recorder'

When I ran the script a week or so ago, it worked fine and I was able to record and watch the simulations, so I'm not sure why it no longer works. I've disconnected and deleted the runtime as well. I'm fairly new to Python, so maybe I'm doing something wrong.

**Comment by XianghaoMeng** [comment] 2024-11-09 14:14
i have the same problem, I ran the same code 1 week ago and it worked well. But now it puts the same error as yours.

**Comment by eleurent** [comment] 2024-11-12 23:38
Looks like this was caused by an update of gymnasium.
Should be fixed at head now.

**Closed** 2024-11-12 23:38 UTC

**Comment by ishparsh** [comment] 2024-11-13 01:14
The issue still persist !! @eleurent

**Comment by carterwg7** [comment] 2024-11-21 21:47
I'm still having trouble even when I install the dev version. For some reason gymnasium doesn't install. Is there a way to install high-env pre usual, and then only install the changed code in highway_env/envs/common/abstract.py?

**Comment by eleurent** [comment] 2024-12-01 11:39
Here's a copy of the colab notebook where I just changed the higheayenv install command to get the dev version (and I reduced the number of training steps to 20 for quick testing): https://colab.research.google.com/drive/1CE0gI2cgNFwAGbfiAgGju-by5h7ZTj0B?usp=sharing

It's working fine for me, can you try to run it?
